"""empty message

Revision ID: 4066a04840ac
Revises: 0cbf3a5b62ba
Create Date: 2022-01-27 13:06:43.059245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4066a04840ac'
down_revision = '0cbf3a5b62ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('img', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'img')
    # ### end Alembic commands ###
